n1=float(input('Primeira nota do aluno: '))
n2=float(input('Segunda nota do aluno: '))
m=((n1+n2)/2)
print(f'A media entre {n1} e {n2} e igual a {m :.1f}')
print(f'A media entre {n1} e {n2} e igual a {(n1+n2)/2 :.1f}')
