x=input('Digite um valor:')
print('O tipo primitivo desse valor e {}'.format(type(x)))
print('So tem espacos? {}'.format(x.isspace()))
print('E Numero? {}'.format(x.isnumeric()))
print('E Alfabetico? {}'.format(x.isalpha()))
print('E Alfanumerico? {}'.format(x.isalnum()))
print('Esta maiusculo? {}'.format(x.isupper()))
print('Esta minusculo? {}'.format(x.islower()))
print('Esta capitalizada? {}'.format(x.istitle()))