x=input('Digite qualquer coisa: ')
print('O tipo primitivo desse valor eh {}'.format(type(x)))
print('tem espaco?',x.isspace())
print('e numerico? ',x.isnumeric())
print('Alfabetico: ',x.isalpha())
print('alfanumerico: ',x.isalnum())
print('Esta em Minuscula?',x.islower())
print('Esta em Maiuscula?',x.isupper())
print('Esta Capitalizada?',x.istitle())
print('boolean',bool(x))
