a= input('Digite qualquer coisa:')
print(f'O tipo de primitivo e {type(a)}')
print(f'So tem espaco? {a.isspace()}')
print(f'E um numero {a.isnumeric()}')
print(f'E alfabetico? {a.isalpha()}')
print(f'E Alfanumerico? {a.isalnum()}')
print(f'Esta maisculo? {a.isupper()}')
print(f'Esta minusculo? {a.islower()}')
print(f'Esta em capitalizada? {a.istitle()}')
